<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tutup_buku extends CI_Controller
{
    public $nama_template='template_admin';
    public $priode='';

    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_Tutup_Buku');
        $this->load->library('form_validation');        
	      $this->load->library('datatables');
        $this->priode_hari=get_option('buka_timbangan');
    }

    public function index()
    {
        $data['hari']='';
        $data['bulan']='';
        
        if ($this->priode_hari) {
          $data['hari']=date_format(date_create($this->priode_hari),"d/m/Y");
        }
        $this->template->load($this->nama_template,'tutup_buku',$data);
    }
    
    public function buka_timbangan()
    {
      update_option('buka_timbangan',current_time( 'mysql' ));
      $this->session->set_flashdata('message_success', 'Berhasil Buka Timbangan');
      redirect(base_url('timbangan'));
    }

    public function eod()
    {

        if (isset($_POST['buka'])) {
          
          redirect(base_url('tutup_buku/buka_timbangan'));
          
        }
        $priode=get_option('buka_timbangan');
        $this->Model_Tutup_Buku->eod('timbangan_h_penimbangan',$priode);
        update_option('buka_timbangan','');
        $this->session->set_flashdata('message_success', 'Berhasil EOD Timbangan');
        redirect(base_url('tutup_buku'));
      
    }
    
    
}

/* End of file daftar_struk.php */
/* Location: ./application/controllers/M_kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-02 07:57:08 */
/* http://harviacode.com */