<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Konfigurasi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->helper('nuris_helper');
        
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    $user = wp_get_current_user();
        if ( !in_array( 'admin', (array) $user->roles ) ) {
                
                redirect(base_url('denied'));
            }
        
    }

    public function index()
    {
        $this->template->load('template_admin','konfigurasi');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Model_coa->json();
    }
    
    public function aksi($option = 'kelipatan_point')
    {
        $value=$_POST['value'];
        if (update_option($option,$value)) {
            $this->session->set_flashdata('message', 'Berhasil Mengubah');
            redirect(base_url('konfigurasi'));
        }
        else {
            $this->session->set_flashdata('message', 'Terjadi Kesalahan');
            redirect(base_url('konfigurasi'));
        }
        
    }

    

}

/* End of file M_coa.php */
/* Location: ./application/controllers/M_coa.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-10 04:22:50 */
/* http://harviacode.com */