<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Akuntansi_m_coa_model extends CI_Model
{

    public $table = 'akuntansi_m_coa';
    public $id = 'uniqid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('uniqid,id_coa,id_kelompok_coa,id_kategori,nama_coa,uniqid_sub,saldo_awal,saldo_normal_special,quantity');
        $this->datatables->from('akuntansi_m_coa');
        //add this line for join
        //$this->datatables->join('table2', 'akuntansi_m_coa.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('akuntansi_m_coa/read/$1'),'Read')." | ".anchor(site_url('akuntansi_m_coa/update/$1'),'Update')." | ".anchor(site_url('akuntansi_m_coa/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'uniqid');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('uniqid', $q);
	$this->db->or_like('id_coa', $q);
	$this->db->or_like('id_kelompok_coa', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_coa', $q);
	$this->db->or_like('uniqid_sub', $q);
	$this->db->or_like('saldo_awal', $q);
	$this->db->or_like('saldo_normal_special', $q);
	$this->db->or_like('quantity', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('uniqid', $q);
	$this->db->or_like('id_coa', $q);
	$this->db->or_like('id_kelompok_coa', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_coa', $q);
	$this->db->or_like('uniqid_sub', $q);
	$this->db->or_like('saldo_awal', $q);
	$this->db->or_like('saldo_normal_special', $q);
	$this->db->or_like('quantity', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Akuntansi_m_coa_model.php */
/* Location: ./application/models/Akuntansi_m_coa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-25 13:59:40 */
/* http://harviacode.com */