<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dashboard extends CI_Controller
{
    public $user='';

    function __construct()
    {
        parent::__construct();
        $this->load->library('form_validation');        
	    $this->load->library('datatables');

        $this->user = wp_get_current_user();
        
    }

    public $nama_template='template_admin';

    public function index()
    {
        $this->template->load($this->nama_template,'dashboard-timbangan');
        $this->load->view('v_komponen');
        
        
    } 

}

/* End of file daftar_struk.php */
/* Location: ./application/controllers/M_kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-02 07:57:08 */
/* http://harviacode.com */