<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_Daftar_Struk extends CI_Model
{

    public $table = 'h_transaksi';
    public $id = 'uniqid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('uniqid_header as uniqid,id_timbang,eod as waktu_timbang,status_timbang as status');
        $this->datatables->from('timbangan_laporan_penimbangan');
        //add this line for join
        //$this->datatables->join('table2', 'Daftar_struk.field = table2.field');
        $this->datatables->add_column('action', anchor(base_url('daftar_struk/read/$1'),'Print Ulang'), 'uniqid');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // Status print
    function status_print($id)
    {
		$this->db->where('uniqid',$id);
		$this->db->set('status_print','status_print+1',FALSE);
        $this->db->update('timbangan_h_penimbangan');
    }

    // get data by id
    function get_by_id($id)
    {
        
        $this->db->select('*');
        $this->db->from('timbangan_laporan_penimbangan');
		$this->db->where('uniqid_header',$id);
        $this->db->group_by('uniqid_header');
        
		return $this->db->get()->row_array();
		
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('uniqid', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_kategori', $q);
	$this->db->or_like('urutan', $q);
	$this->db->or_like('isi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('uniqid', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_kategori', $q);
	$this->db->or_like('urutan', $q);
	$this->db->or_like('isi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function ubahstatus($uniqid,$data)
{
    
    $this->db->where('uniqid', $uniqid);
    $this->db->where('status_timbang', 0);
    $this->db->update('timbangan_h_penimbangan', $data);
    
}


}

/* End of file Model_kategori.php */
/* Location: ./application/models/Model_kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-02 07:57:08 */
/* http://harviacode.com */